# Generated by Django 2.2.6 on 2019-11-06 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attachment', '0001_initial'),
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='last_read_messages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Message.message'),
        ),
    ]
