# Generated by Django 2.2.6 on 2019-11-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0003_auto_20191125_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='audio',
            field=models.FileField(null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
