version: '3.6'
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/dockerfile-prod
    volumes:
      - ./.caddy:/root/.caddy  # to save certificates on disk
      - ./docker/frontend/Caddyfile:/etc/Caddyfile  # to mount custom Caddyfile
    ports:
      - "2015:2015"
      - "80:80"
      - "443:443"
