# Generated by Django 2.2.6 on 2019-11-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trashchat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('added_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
