# Generated by Django 2.2.6 on 2019-11-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachment', '0002_auto_20191106_0617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='last_read_messages',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='new_messages',
        ),
    ]
